# Generated by Django 2.2.17 on 2021-07-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'QA',
                'verbose_name_plural': 'QAs',
            },
        ),
        migrations.CreateModel(
            name='AlternateQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=200)),
                ('main_qa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_questions', to='vosa.QA')),
            ],
            options={
                'verbose_name': 'aQ',
                'verbose_name_plural': 'aQs',
            },
        ),
    ]
