# Generated by Django 2.2.17 on 2021-07-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vosa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAKB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.TextField(choices=[('PRODUCT', 'PRODUCT'), ('SERVICE', 'SERVICE'), ('TOPIC', 'TOPIC')], default='TOPIC', max_length=20)),
            ],
            options={
                'verbose_name': 'QAKB',
                'verbose_name_plural': 'QAKBs',
            },
        ),
        migrations.AlterField(
            model_name='alternateq',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Alternative Question'),
        ),
        migrations.AddField(
            model_name='qa',
            name='qakb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_qa', to='vosa.QAKB'),
            preserve_default=False,
        ),
    ]
