# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 09:46
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(b'FIRST', 1), (b'SECOND', 2), (b'THIRD', 3), (b'FOURTH', 4), (b'FIFTH', 5)], default=1, help_text=b'A category with a high priority will have its content having a higher visibility precendence than others. FIRST is the highest.')),
                ('on_nav', models.BooleanField(default=False, help_text=b'If set, then this category will have an entry on the navigation menu', verbose_name=b'On Nav?')),
                ('child_of', models.ForeignKey(help_text=b'Under which category should this one be nested?', on_delete=django.db.models.deletion.CASCADE, related_name='my_children', to='engine.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(b'FIRST', 1), (b'SECOND', 2), (b'THIRD', 3), (b'FOURTH', 4), (b'FIFTH', 5)], default=1, help_text=b'A page with a high priority will have its content having a higher visibility precendence than others. FIRST is the highest.')),
                ('on_nav', models.BooleanField(default=False, help_text=b'If set, then this category will have an entry on the navigation menu', verbose_name=b'On Nav?')),
                ('content', models.TextField(blank=True, null=True)),
                ('accent_color', colorfield.fields.ColorField(default=b'#000', max_length=18)),
                ('category', models.ForeignKey(help_text=b'Under which category should this page be nested?', on_delete=django.db.models.deletion.CASCADE, related_name='my_pages', to='engine.Category')),
            ],
        ),
    ]
