# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='child_of',
            field=models.ForeignKey(blank=True, help_text=b'Under which category should this one be nested?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_children', to='engine.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, b'FIRST'), (2, b'SECOND'), (3, b'THIRD'), (4, b'FOURTH'), (5, b'FIFTH')], default=1, help_text=b'A category with a high priority will have its content having a higher visibility precendence than others. FIRST is the highest.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, b'FIRST'), (2, b'SECOND'), (3, b'THIRD'), (4, b'FOURTH'), (5, b'FIFTH')], default=1, help_text=b'A page with a high priority will have its content having a higher visibility precendence than others. FIRST is the highest.'),
        ),
    ]
