# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 13:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20180323_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='site_about',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=b'Welcome! This Site is Still Under Construction', help_text=b'What you put here, will be shown to the public, to allow them to know what this website is about'),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_accent_color',
            field=colorfield.fields.ColorField(default=b'#78a63e', max_length=18),
        ),
    ]
