# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 09:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20180323_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField(blank=True, editable=False, null=True)),
                ('accent_color', colorfield.fields.ColorField(default=b'#78a63e', max_length=18)),
                ('welcome_message', ckeditor_uploader.fields.RichTextUploadingField(default=b'Welcome! Enjoy it while we build it!', help_text=b'Default message on the home page/landing page.')),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
        migrations.DeleteModel(
            name='SettingsOverride',
        ),
        migrations.AddField(
            model_name='page',
            name='override_css',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
    ]
