# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20180326_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='categories_title',
            field=models.CharField(default=b'Categories', max_length=20),
        ),
    ]
