# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_settings_categories_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='on_landing',
            field=models.BooleanField(default=True, help_text=b'If set, then this page will show up on the default landing page', verbose_name=b'On Landing?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='on_nav',
            field=models.BooleanField(default=False, help_text=b'If set, then this page will have an entry on the navigation menu', verbose_name=b'On Nav?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='override_css',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='categories_title',
            field=models.CharField(default=b'Categories', max_length=20, verbose_name=b'Categories Title'),
        ),
    ]
