# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20180327_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=engine.models.page_image_upload_to),
        ),
    ]
