# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 17:26
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20180327_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text=b'The summary or brief of the contents of this page -- used on preview tiles', null=True),
        ),
    ]
