# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20180327_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['priority', '-id', '-created']},
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='card_columns',
            field=models.PositiveSmallIntegerField(choices=[(1, b'ONE'), (2, b'TWO'), (3, b'THREE'), (4, b'FOUR'), (4, b'FIVE')], default=3, help_text=b'How many card columns to show per row?'),
        ),
    ]
