# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 07:41
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_auto_20180327_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='site_fore_color',
            field=colorfield.fields.ColorField(default=b'#ffffff', max_length=18),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_name',
            field=models.CharField(default=b'Site Under Construction', max_length=32),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='card_columns',
            field=models.PositiveSmallIntegerField(choices=[(1, b'ONE'), (2, b'TWO'), (3, b'THREE'), (4, b'FOUR'), (5, b'FIVE')], default=3, help_text=b'How many card columns to show per row?'),
        ),
    ]
