# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_auto_20180330_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='site_brand_image',
            field=models.ImageField(blank=True, null=True, upload_to=engine.models.site_logo_image_upload_to),
        ),
    ]
