# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_settings_site_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='card_columns',
            field=models.PositiveSmallIntegerField(choices=[(1, b'ONE'), (2, b'TWO'), (3, b'THREE'), (4, b'FOUR'), (5, b'FIVE')], default=3, help_text=b'On grid pages, how many card columns to show per row?'),
        ),
    ]
