# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_settings_card_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='on_menu',
            field=models.BooleanField(default=False, help_text=b'If set, then this category will have an entry on the categories menu', verbose_name=b'On Menu?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='on_nav',
            field=models.BooleanField(default=False, help_text=b'If set, then this category will have an entry on the navigation bar', verbose_name=b'On Nav?'),
        ),
    ]
