# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20190110_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_icon',
            field=models.ImageField(blank=True, help_text=b'This image will act as the page icon in navigation and on preview uis', null=True, upload_to=engine.models.page_image_upload_to),
        ),
    ]
