# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_auto_20190402_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='show_welcome_message',
            field=models.BooleanField(default=True, help_text=b'If set, then the welcome message below will be rendered on the Home page', verbose_name=b'Show Welcome?'),
        ),
    ]
